### ISSUE TITLE
Create routing and mocks for group list

### ISSUE THREAD

**Issue by a-legotin** [C3Junior/c3-web-next#21]

**Comment by GRomR1** [comment]
Группы, рабочие группы, пользотельские группы.
c3web -> src -> main -> scala -> org.aphreet.c3 -> snippet -> groups   --- классы вызываемые при получении списка групп
c3web -> src -> main -> scala -> org.aphreet.c3 -> model   --- классы модели

Запуск проекта
c3web -> src -> main -> test -> RunWebApp  --- ПКМ -> Run

**Comment by a-legotin** [comment]
resolved, merged to main
