### ISSUE TITLE
Font-Awesome icon to home.html

### ISSUE THREAD

**Issue by PartyLeader** [C3Junior/c3-web-next#22]
Need see all Font-Awesome icons and select icon for:
* Communication
* Collaboration
* Content

Source:
http://fortawesome.github.io/Font-Awesome/icons/

**Comment by a-legotin** [comment]
My suggestion is:
Communication: http://fortawesome.github.io/Font-Awesome/icon/commenting/
Collaboration: http://fortawesome.github.io/Font-Awesome/icon/users/
Content: http://fortawesome.github.io/Font-Awesome/icon/file-text-o/
And additional special icon: http://fortawesome.github.io/Font-Awesome/icon/beer/

**Comment by a-legotin** [comment]
icons changes, closed
